acmucsd/acm-ai-site

src/actions/auth.ts, src/actions/dimensions/tournament.ts, src/pages/UploadNNPage/index.tsx
=> NN Submission Form

src/App.tsx, src/actions/auth.ts, src/actions/dimensions/tournament.ts, src/pages/Auth/LoginPage/index.tsx, src/pages/Auth/RequestReset/index.less, src/pages/Auth/RequestReset/index.tsx, src/pages/UploadNNPage/index.tsx
Created new page for requesting password reset from login page, and linked it to API
=> Request reset

package-lock.json, src/actions/competition.ts, src/components/CheckableTagList/index.less, src/components/CheckableTagList/index.tsx, src/pages/Competitions/CompetitionUploadPage/index.less, src/pages/Competitions/CompetitionUploadPage/index.tsx
I've added the description and a way to add a list of checkable tags of any length.
I've also made the `uploadSubmission()` function take `desc` (a string containing the description) and `tagsSelected` (an array with the tags selected) as params. Note that I haven't added any code to do anything with the params as I was told not to bother with post requests; as of now they're basically just passed as params and never used.
Pls lmk if you'd like me to
1. add a max character count to the description, and what that max count would be
2. try to add any styling to the tags (though `antd` seems pretty strict here; from my reserach devs don't wanna add support for even something like a color tag)
3. any other changes you'd like me to implement
link to check changes: …
=> add checkable tags (make component) + desc section to upload page; pass to uploadSubmission()

src/components/Header/index.tsx
per jon's request https://discord.com/channels/573028991527550986/712861186688942121/1026659123271577730
=> change menu bar navigation order

package-lock.json, src/components/Card/index.less, src/components/ProjectCard/index.less, src/components/ProjectCard/index.tsx, src/pages/ProjectsPage/index.tsx
=> Projects modal

src/pages/Competitions/CompetitionLeaderboardPage/index.tsx
Resolves issue #56 
Modified old leaderboard page
Tables are now sortable
Columns: rank, team name, score, entries
Currently contains fake data
=> Competitions v2 Leaderboard

src/pages/Competitions/CompetitionUploadPage/index.less, src/pages/Competitions/CompetitionUploadPage/index.tsx
=> Add any number up to 10 tags to submission

package-lock.json, package.json, src/pages/Competitions/CompetitionLandingPage/index.less, src/pages/Competitions/CompetitionLandingPage/index.tsx
Added markdown rendering for landing page using react-remark package
Markdown is currently hardcoded into the component, easily changeable
Resolves #67
=> Added markdown rendering for landing page

src/actions/teams/utils.ts, src/pages/Competitions/CompetitionTeamPages/AllTeamsPage/index.less, src/pages/Competitions/CompetitionTeamPages/AllTeamsPage/index.tsx
=> Team creation form on all teams page

src/App.tsx, src/actions/teams/utils.ts, src/pages/Competitions/CompetitionTeamPages/JoinTeamsPage/index.less, src/pages/Competitions/CompetitionTeamPages/JoinTeamsPage/index.tsx
=> Competitions add to team

src/actions/competition.ts, src/pages/Competitions/CompetitionLandingPage/index.tsx
=> Register user to view/make teams, upload

src/App.tsx, src/actions/teams/utils.ts, src/pages/Competitions/CompetitionTeamPages/SubmissionDetailsPage/index.less, src/pages/Competitions/CompetitionTeamPages/SubmissionDetailsPage/index.tsx
Just prints raw data right now. Does not require authorization to view
Resolves issue #80
=> Add submissions details page

package-lock.json, src/actions/teams/utils.ts, src/pages/Competitions/CompetitionTeamPages/AllTeamsPage/index.less, src/pages/Competitions/CompetitionTeamPages/AllTeamsPage/index.tsx, src/pages/Competitions/CompetitionTeamPages/SpecificTeamPage/index.less, src/pages/Competitions/CompetitionTeamPages/SpecificTeamPage/index.tsx
- slightly changed error message
- removed red header in team pages
- added back buttons to team pages
- added table of current user's team's submissions in their specific team page, only shows up when user clicks on their specific team page
Notes:
- hardcoded submission IDs because the seeding data didn't have anything in the teams submitHistory (just uncomment the code below the hardcoded IDs for the real thing)
=> Team submissions list on specific team page and minor fixes

src/pages/MainPage/index.less, src/pages/MainPage/index.tsx
https://github.com/acmucsd/acm-ai-site/assets/33042752/9f79da82-0c23-4ef5-aceb-fc662b7f8eb5
=> Replace main page carousel

src/App.tsx, src/actions/auth.ts, src/actions/events.ts, src/pages/Auth/RegisterPage/index.less, src/pages/Auth/RegisterPage/index.tsx, src/pages/Competitions/CompetitionPortalPage/index.less, src/pages/Competitions/CompetitionPortalPage/index.tsx, src/pages/CompetitionsPage/index.less, src/pages/CompetitionsPage/index.tsx
- Added the admin checkbox to user registration. 
- Created new route for the competition portal page `/competitionPortal` to `App.tsx`
- Portal Page has basic formatting and styling
=> Auth add admin

src/components/MainFooter/index.tsx
Updated links to apply for different positions at ACM AI. Links lead to most recent overall ACM AI application form.
=> fixed acm ai apply links

src/App.tsx, src/pages/404Page/index.less, src/pages/404Page/index.tsx
=> 404 Page Not Found Route and Component

public/index.html
Tested with localtunnel library (thanks Sam for the info!)
Resolves #130
=> Link preview

src/components/MainFooter/index.tsx
- add newsletter link 
- change footer links to open in new tab
=> fix: update footer with newsletter link

src/components/Header/index.less
Made mobileDropdown display to none unless it's toggled to open. 
Fix bug/issue #112
=> Navbar bug fix

src/pages/AboutPage/people.ts
bugs that this fixes:
- when going to about page directly, it doesn't seem to load
- seems to be using cached version of bios.csv even though network request is being made to gsheets
todo
- should probably cache this instead so it updates every 24 hours instead of doing api calls every time but i dont expect it do get more than [300 requests/min](https://developers.google.com/sheets/api/limits) so eh
- make this done with a service account for google perms
=> fix: live updates for board bios

src/pages/AboutPage/index.tsx, src/pages/AboutPage/people.ts, src/pages/MainPage/index.less
=> fix about info loading

src/components/MainFooter/index.less
=> Your footer is BIG

src/components/CompetitionDiscordLink/index.tsx, src/components/MainFooter/index.tsx, src/pages/Competitions/CompetitionLandingPage/index.less, src/pages/Competitions/CompetitionLandingPage/index.tsx, src/pages/Competitions/CompetitionLeaderboardPage/index.tsx, src/pages/CompetitionsPage/competition.ts, src/pages/CompetitionsPage/competitionsData.json
closes #88
no more uploading predictions when no comp
=> Add signup button and hide upload preds for nonactive comps

src/components/Header/index.tsx, src/pages/Competitions/CompetitionPortalPage/index.tsx, src/pages/Competitions/CompetitionUploadPage/index.less, src/pages/Competitions/CompetitionUploadPage/index.tsx, src/pages/CompetitionsPage/index.tsx
- give the upload page room to breathe
- new dropdown with portal/profile/logout when logged in
=> dropdown menu and various css fixes

src/pages/ProfilePage/index.less, src/pages/ProfilePage/index.tsx
- added prominent section leading to competitions
- added cards leading to about and projects pages
=> add explore section on profile page

src/pages/AboutPage/index.tsx, src/pages/AboutPage/people.ts
- change about page to reflect 25-26 board
- profile pictures from google drive don't work, so just use ai diamond for now
=> change about page to reflect 25-26 board

src/pages/CompetitionsPage/competitionsData.json
- added number of submissions and teams
=> Add StarChess stats to competitions page
